"""C_10_2342349

Revision ID: 10d49de12432
Revises: 1c793e5bd95c
Create Date: 2015-12-02 11:22:45.035441

"""

# revision identifiers, used by Alembic.
revision = '10d49de12432'
down_revision = '1c793e5bd95c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    ### end Alembic commands ###
