"""token

Revision ID: 18077ff249f2
Revises: 1e40103807fb
Create Date: 2015-10-09 22:58:06.572784

"""

# revision identifiers, used by Alembic.
revision = '18077ff249f2'
down_revision = '1e40103807fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
