"""C_10_34829

Revision ID: 1c793e5bd95c
Revises: 43de36d2b4a9
Create Date: 2015-12-01 16:36:21.534801

"""

# revision identifiers, used by Alembic.
revision = '1c793e5bd95c'
down_revision = '43de36d2b4a9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_column('roles', 'permissions')
    op.add_column('users', sa.Column('locate', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'avatar_hash')
    op.drop_column('users', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'locate')
    op.add_column('roles', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_column('roles', 'permission')
    ### end Alembic commands ###
