"""Permision

Revision ID: 20145c96799f
Revises: 4bc602c522ba
Create Date: 2015-11-16 23:02:22.677228

"""

# revision identifiers, used by Alembic.
revision = '20145c96799f'
down_revision = '4bc602c522ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
