"""gravatar

Revision ID: 2892bc158bd4
Revises: 30831614a021
Create Date: 2015-11-05 17:55:23.728950

"""

# revision identifiers, used by Alembic.
revision = '2892bc158bd4'
down_revision = '30831614a021'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
