"""initial migrate

Revision ID: 4fd506e671ae
Revises: None
Create Date: 2015-10-01 15:48:04.979396

"""

# revision identifiers, used by Alembic.
revision = '4fd506e671ae'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
