"""C_10_gravatar_1

Revision ID: 5fd664168
Revises: None
Create Date: 2015-12-08 17:13:48.996759

"""

# revision identifiers, used by Alembic.
revision = '5fd664168'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
