"""C_11.4_12-18

Revision ID: 78def2ebe5c
Revises: None
Create Date: 2015-12-18 15:45:11.808093

"""

# revision identifiers, used by Alembic.
revision = '78def2ebe5c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
