"""C_13_12-30

Revision ID: d6be256b25da
Revises: d53031109960
Create Date: 2015-12-30 11:53:53.674893

"""

# revision identifiers, used by Alembic.
revision = 'd6be256b25da'
down_revision = 'd53031109960'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disable', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_table('comments')
    ### end Alembic commands ###
