"""Permission

Revision ID: e5dea8fcd26
Revises: 20145c96799f
Create Date: 2015-11-16 23:07:11.199583

"""

# revision identifiers, used by Alembic.
revision = 'e5dea8fcd26'
down_revision = '20145c96799f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', 'roles')
    op.drop_column('roles', 'permission')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
